import "./globals.css";

import type { Metadata } from "next";

import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { ThemeProvider } from "@/components/theme-provider";
import { DocsSidebar } from "@/features/docs-sidebar/DocsSidebar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning >
      <body>
        <ThemeProvider>
          <Header/>

          {/*
            flex-grow: This tells the main content to take up ALL available
            space, pushing the footer to the bottom.
          */}
          <main className="m3-container flex flex-grow">
            <div className="flex-none">
              <DocsSidebar />
            </div>
            
            {/* Content: Takes up all remaining space */}
            <div className="grow p-6">
              {children}
            </div>
          </main>
          
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
